In [1]:
from PIL import Image
import numpy as np

In [2]:
image = Image.open("images/cat_2.jpg").convert("L")
image = np.array(image)

In [3]:
agf = np.array((([1,1,1], [1,2,1], [1,1,1])), dtype=np.float32) * 1/10
ygf = np.array((([0,-1,0], [-1,10,-1], [0,-1,0])), dtype=np.float32) 

print(agf)
print(ygf)

[[0.1 0.1 0.1]
 [0.1 0.2 0.1]
 [0.1 0.1 0.1]]
[[ 0. -1.  0.]
 [-1. 10. -1.]
 [ 0. -1.  0.]]


In [4]:
def apply_filter(image, kernel):
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape

    pad_x = kernel_width // 2
    pad_y = kernel_height // 2

    image = np.pad(image, ((pad_y, pad_y), (pad_x, pad_x)), mode='reflect') 
    output= np.zeros_like(image, dtype=np.float32)

    for x in range(image_width):
        for y in range(image_height):
            region = image[y:y+kernel_height, x:x+kernel_width]
            output[y,x] = (region * kernel).sum()

    output = np.clip(output, 0, 255).astype(np.uint8)
    return output

In [5]:
output_agf = apply_filter(image, agf)
output_ygf = apply_filter(image, ygf)

print(output_agf.max())
print(output_agf.min())
print(output_agf.shape)

print(output_ygf.max())
print(output_ygf.min())
print(output_ygf.shape)

output_agf = Image.fromarray(output_agf)
output_ygf = Image.fromarray(output_ygf)

output_agf.save("images/cat_2_agf.jpg")
output_ygf.save("images/cat_2_ygf.jpg")

199
0
(855, 1282)
255
0
(855, 1282)
